import { HitTPUpdateInputs, SignalResult, LotSizeResult, HitTPUpdateResult, HitTPStatus } from "../types/calculator";

export const getHitTPStatusLabel = (status: HitTPStatus): string => {
  switch (status) {
    case "tp1": return "TP1 HIT";
    case "tp2": return "TP2 HIT";
    case "tp3": return "TP3 HIT";
    case "tp4": return "TP4 HIT";
    case "alltp": return "ALL TP HIT";
    case "sl": return "SL HIT";
    case "entry": return "ENTRY TRIGGERED";
    case "be": return "BREAK EVEN ACTIVATED";
    case "manual": return "MANUAL UPDATE";
    default: return "";
  }
};

export const generateHitTPPlainTextUpdate = (
  inputs: HitTPUpdateInputs,
  signal: SignalResult,
  lotSize: LotSizeResult,
  score: number,
  grade: string
): string => {
  const statusLabel = getHitTPStatusLabel(inputs.status);
  const direction = signal.direction;
  const timeframe = signal.timeframe;

  let msg = `XAUUSD ${direction} UPDATE\n\n`;
  msg += `Timeframe: ${timeframe}\n`;
  msg += `Status: ${statusLabel.toUpperCase()}\n\n`;

  // Specific status templates
  if (inputs.status === "alltp") {
    msg += `TP1: ${signal.tp1.toFixed(2)} HIT\n`;
    msg += `TP2: ${signal.tp2.toFixed(2)} HIT\n`;
    msg += `TP3: ${signal.tp3.toFixed(2)} HIT\n`;
    msg += `TP4: ${signal.tp4.toFixed(2)} HIT\n\n`;
    msg += `Trade Result:\nAll targets reached successfully.\n\n`;
    msg += `Total Estimated Net Profit: $${(lotSize.profits.tp1.net + lotSize.profits.tp2.net + lotSize.profits.tp3.net + lotSize.profits.tp4.net).toFixed(2)}\n`;
  } else if (inputs.status === "sl") {
    msg += `Entry Zone: ${signal.entryZoneLow.toFixed(2)} - ${signal.entryZoneHigh.toFixed(2)}\n`;
    msg += `SL: ${signal.sl.toFixed(2)}\n\n`;
    if (inputs.includeProfitEstimate) msg += `Estimated Loss: -$${lotSize.estimatedLoss.toFixed(2)}\n\n`;
    msg += `Management:\nTrade closed by stop loss. Wait for next valid setup.\n`;
  } else if (inputs.status === "be") {
    msg += `New SL: ${signal.conservativeEntry.toFixed(2)}\n`;
    msg += `Original SL: ${signal.sl.toFixed(2)}\n\n`;
    msg += `Management:\nRisk removed. Hold remaining position according to TP plan.\n`;
  } else if (inputs.status === "entry") {
    msg += `Entry Zone: ${signal.entryZoneLow.toFixed(2)} - ${signal.entryZoneHigh.toFixed(2)}\n`;
    msg += `SL: ${signal.sl.toFixed(2)}\n`;
    msg += `TP1: ${signal.tp1.toFixed(2)}\n`;
    msg += `TP2: ${signal.tp2.toFixed(2)}\n`;
    msg += `TP3: ${signal.tp3.toFixed(2)}\n`;
    msg += `TP4: ${signal.tp4.toFixed(2)}\n\n`;
    msg += `Management:\nWait for TP1. Move SL to BE after TP1 if selected.\n`;
  } else if (inputs.status.startsWith("tp")) {
    const num = inputs.status.replace("tp", "");
    const tpPrice = signal[inputs.status as keyof SignalResult] as number;
    const tpDist = signal[`${inputs.status}Distance` as keyof SignalResult] as number;
    const partialPercent = 25; // Default assumption based on prompt
    const profit = lotSize.profits[inputs.status as keyof typeof lotSize.profits].net;

    msg += `Entry Zone: ${signal.entryZoneLow.toFixed(2)} - ${signal.entryZoneHigh.toFixed(2)}\n`;
    msg += `${statusLabel.toUpperCase()}: ${tpPrice.toFixed(2)}\n\n`;
    
    if (inputs.includeProfitEstimate) {
      msg += `Estimated Profit ${statusLabel.toUpperCase()}: $${profit.toFixed(2)}\n`;
      msg += `Partial Close: ${partialPercent}%\n\n`;
    }

    msg += `Management:\n`;
    if (inputs.status === "tp1") {
      msg += `Move SL to BE after TP1.\nHold remaining position for TP2, TP3, TP4.\n`;
    } else if (inputs.status === "tp2") {
      msg += `If SL is already at BE, continue holding remaining position for TP3 and TP4.\n`;
    } else if (inputs.status === "tp3") {
      msg += `Secure profit. Hold final runner only if market structure remains valid.\n`;
    } else if (inputs.status === "tp4") {
      msg += `Final target reached. Trade completed.\n`;
    }
  }

  if (inputs.currentPrice) {
    msg += `\nCurrent Price: ${inputs.currentPrice.toFixed(2)}\n`;
  }

  if (inputs.status === "tp1" && score >= 0) {
    msg += `\nTrade Quality Score: ${score}/100\nGrade: ${grade}\n`;
  }

  if (inputs.customNote) {
    msg += `\nNote: ${inputs.customNote}\n`;
  } else if (inputs.status === "tp1") {
    msg += `\nNote: Price reached TP1. Manage risk and secure profit.\n`;
  } else if (inputs.status === "sl") {
     msg += `\nNote: Risk was controlled according to plan.\n`;
  }

  if (inputs.includeTimestamp) {
    msg += `\nGenerated on: ${new Date().toLocaleString()}\n`;
  }
  
  if (inputs.includeFooter) {
    msg += `\nGenerated by XAUUSD Gann Square of Nine Pro Calculator`;
  }

  return msg;
};

export const generateHitTPHtmlUpdate = (
  inputs: HitTPUpdateInputs,
  signal: SignalResult,
  lotSize: LotSizeResult,
  score: number,
  grade: string
): string => {
  const statusLabel = getHitTPStatusLabel(inputs.status);
  const direction = signal.direction;
  
  let msg = `<b>XAUUSD ${direction} UPDATE</b>\n\n`;
  msg += `<b>Timeframe:</b> ${signal.timeframe}\n`;
  msg += `<b>Status:</b> ${statusLabel.toUpperCase()}\n\n`;

  if (inputs.status === "alltp") {
    msg += `<b>TP1:</b> ${signal.tp1.toFixed(2)} HIT\n`;
    msg += `<b>TP2:</b> ${signal.tp2.toFixed(2)} HIT\n`;
    msg += `<b>TP3:</b> ${signal.tp3.toFixed(2)} HIT\n`;
    msg += `<b>TP4:</b> ${signal.tp4.toFixed(2)} HIT\n\n`;
    msg += `<b>Trade Result:</b>\nAll targets reached successfully.\n\n`;
    msg += `<b>Total Estimated Net Profit:</b> $${(lotSize.profits.tp1.net + lotSize.profits.tp2.net + lotSize.profits.tp3.net + lotSize.profits.tp4.net).toFixed(2)}\n`;
  } else if (inputs.status === "sl") {
    msg += `<b>Entry Zone:</b> ${signal.entryZoneLow.toFixed(2)} - ${signal.entryZoneHigh.toFixed(2)}\n`;
    msg += `<b>SL:</b> ${signal.sl.toFixed(2)}\n\n`;
    if (inputs.includeProfitEstimate) msg += `<b>Estimated Loss:</b> -$${lotSize.estimatedLoss.toFixed(2)}\n\n`;
    msg += `<b>Management:</b>\nTrade closed by stop loss. Wait for next valid setup.\n`;
  } else if (inputs.status.startsWith("tp")) {
    const tpPrice = signal[inputs.status as keyof SignalResult] as number;
    const profit = lotSize.profits[inputs.status as keyof typeof lotSize.profits].net;

    msg += `<b>Entry Zone:</b> ${signal.entryZoneLow.toFixed(2)} - ${signal.entryZoneHigh.toFixed(2)}\n`;
    msg += `<b>${statusLabel.toUpperCase()}:</b> ${tpPrice.toFixed(2)}\n\n`;
    
    if (inputs.includeProfitEstimate) {
      msg += `<b>Estimated Profit:</b> $${profit.toFixed(2)}\n`;
      msg += `<b>Partial Close:</b> 25%\n\n`;
    }

    msg += `<b>Management:</b>\n`;
    if (inputs.status === "tp1") msg += `Move SL to BE after TP1.\nHold remaining position for TP2, TP3, TP4.\n`;
    else msg += `Manage position according to plan.\n`;
  }

  if (inputs.currentPrice) {
    msg += `\n<b>Current Price:</b> ${inputs.currentPrice.toFixed(2)}\n`;
  }

  if (inputs.customNote) {
    msg += `\n<b>Note:</b> ${inputs.customNote}\n`;
  }

  if (inputs.includeTimestamp) {
    msg += `\n<pre>Generated at: ${new Date().toLocaleString()}</pre>`;
  }

  if (inputs.includeFooter) {
    msg += `\n<i>Generated by XAUUSD Gann Square of Nine Pro Calculator</i>`;
  }

  return msg;
};
