import { SignalResult, LotSizeResult, FiboConfluence } from "../types/calculator";
import { TradeScoreResult } from "./tradeScore";

export const generateTelegramSignalHtml = (
  signal: SignalResult,
  lotSize: LotSizeResult,
  score: TradeScoreResult,
  notes: string = "",
  config?: { includeFooter?: boolean; includeGeneratedOn?: boolean; confluences?: FiboConfluence[] }
): string => {
  const { direction, timeframe, entryZoneLow, entryZoneHigh, conservativeEntry, sl, tp1, tp2, tp3, tp4 } = signal;

  let msg = `<b>📊 XAUUSD ${direction} SIGNAL</b>\n\n`;
  msg += `<b>🕒 Timeframe:</b> ${timeframe}\n`;
  msg += `<b>🎯 Entry Zone:</b> ${entryZoneLow.toFixed(2)} - ${entryZoneHigh.toFixed(2)}\n`;
  msg += `<b>⚡ Conservative Entry:</b> ${conservativeEntry.toFixed(2)}\n\n`;
  
  msg += `<b>🛑 Stop Loss:</b> ${sl.toFixed(2)}\n\n`;
  
  msg += `<b>✅ TP1:</b> ${tp1.toFixed(2)}\n`;
  msg += `<b>✅ TP2:</b> ${tp2.toFixed(2)}\n`;
  msg += `<b>✅ TP3:</b> ${tp3.toFixed(2)}\n`;
  msg += `<b>✅ TP4:</b> ${tp4.toFixed(2)}\n\n`;
  
  msg += `<b>📏 Lot Size:</b> ${lotSize.suggestedLotSize.toFixed(2)}\n`;
  msg += `<b>⭐ Quality Score:</b> ${score.score}/100 (${score.grade})\n\n`;

  if (config?.confluences && config.confluences.length > 0) {
    msg += `<b>🌀 Harmonic Confluences:</b>\n`;
    config.confluences.forEach(c => {
      msg += `• ${c.target} Match @ ${c.label} (${c.strength})\n`;
    });
    msg += `\n`;
  }
  
  if (notes) {
    msg += `<b>📝 Notes:</b>\n${notes}\n\n`;
  }
  
  if (config?.includeFooter !== false) {
    msg += `<i>Powered by XAUUSD Gann Pro Calculator</i>`;
    if (config?.includeGeneratedOn !== false) {
      msg += `\n<pre>Generated at: ${new Date().toLocaleString()}</pre>`;
    }
  } else if (config?.includeGeneratedOn !== false) {
    msg += `<pre>Generated at: ${new Date().toLocaleString()}</pre>`;
  }
  
  return msg;
};

export const generatePlainTextSignal = (
  signal: SignalResult,
  lotSize: LotSizeResult,
  score: TradeScoreResult,
  notes: string = "",
  config?: { includeFooter?: boolean; includeGeneratedOn?: boolean; confluences?: FiboConfluence[] }
): string => {
  const { direction, timeframe, entryZoneLow, entryZoneHigh, conservativeEntry, sl, tp1, tp2, tp3, tp4 } = signal;

  let msg = `XAUUSD ${direction} SIGNAL\n\n`;
  msg += `Timeframe: ${timeframe}\n`;
  msg += `Entry Zone: ${entryZoneLow.toFixed(2)} - ${entryZoneHigh.toFixed(2)}\n`;
  msg += `Conservative Entry: ${conservativeEntry.toFixed(2)}\n\n`;
  
  msg += `Stop Loss: ${sl.toFixed(2)}\n\n`;
  
  msg += `TP1: ${tp1.toFixed(2)}\n`;
  msg += `TP2: ${tp2.toFixed(2)}\n`;
  msg += `TP3: ${tp3.toFixed(2)}\n`;
  msg += `TP4: ${tp4.toFixed(2)}\n\n`;
  
  msg += `Suggested Lot: ${lotSize.suggestedLotSize.toFixed(2)}\n`;
  msg += `Trade Score: ${score.score}/100 (${score.grade})\n\n`;

  if (config?.confluences && config.confluences.length > 0) {
    msg += `Harmonic Confluences:\n`;
    config.confluences.forEach(c => {
      msg += `- ${c.target} Match @ ${c.label} (${c.strength})\n`;
    });
    msg += `\n`;
  }
  
  if (notes) {
    msg += `Notes: ${notes}\n\n`;
  }
  
  if (config?.includeFooter !== false) {
    msg += `Generated by XAUUSD Gann Square of Nine Pro Calculator`;
    if (config?.includeGeneratedOn !== false) {
      msg += `\nDate: ${new Date().toLocaleString()}`;
    }
  } else if (config?.includeGeneratedOn !== false) {
    msg += `Generated on: ${new Date().toLocaleString()}`;
  }
  
  return msg;
};
